    .dropdown {
      float: left;
      width: auto;
    }

    .dropdown-content {
      display: none;
      position: absolute;
      background-color: darken($background-color, 3%);
      min-width: 160px;
      box-shadow: $box-shadow;
      z-index: 1;
    }

    .dropdown-content a {
      padding: 4px 8px;
    }

    .dropdown:hover .dropdown-content {
      display: block;
    }

    .dropdown-content a:not(:last-child){
      border-bottom: none; 
    }