---
title: "Experience"
---

&nbsp;

### Healthfirst
#### Clinical Informatics & Analytics Intern, 2018

&nbsp;

With my internship at Healthfirst I had the opportunity to run analyses investigating the effect distance played in preventable admissions (PQIs) in the Medicaid population with in-patient claims. This data was gathered with the help of Google Maps API in addition to Alteryx for coordinate difference measurements. 

I was also fortunate enough to work within a group to complete a descriptive analysis of opioid abusers in the Medicaid population, using pharmacy data as well as claims.

&nbsp;

###Hunter James Kelly Research Institute
####Research Assistant, 2015 - 2016

&nbsp;

The Hunter James Kelly Research Institute (HJKRI) conducts research investigating myelin and its diseases. 

As a Research Assistant, I collaborated on a 3-person research team and was tasked to work independently in a sterilized environment performing cell culture work. Respected for completing immunohistochemistry staining then analyzing and presenting data to team members and the principal investigator, I was well known for my consistent work ethic and project deliverables.

This position focused on neurology lab experience with a focus on immunohistochemistry staining, Western Blots, DNA extraction, siRNA knockdown, polymerase chain reaction, restriction enzyme digestion, Schwann cell and dorsal root ganglia (DRG) co-culture. I also performed mouse sciatic nerve, rat embryo spinal cord and DRG dissection.

&nbsp;

###Celgene Corporation
#### Global Regulatory CMC, Pharmaceutical Intern, 2013-2016

&nbsp;

Celgene Corporation is an American biotechnology company that manufactures drug therapies for cancer and inflammatory disorders.

During my time as an intern, I helped with the preparation of protocols and documents to support efforts in gaining FDA approval of New Drug Applications (NDAs) for various products. This included updating standard operating procedures (SOPs), quality overall summaries (QOSs), regulatory requirements documents and databases making them more understandable, efficient and applicable to current policies. 

I have also audited and proofread confidential drug trial files and drafted change notices as well as modified, aligned and integrated new acquisition drug trial documents with Celgene's regulatory guidelines.