---
title: "Projects"
---

&nbsp;

###  Healthfirst 
#### November - December 2018

&nbsp;

In-patient Medicaid claims from 2016 and 2017 were gathered and the number of preventable admissions per member was aggregated in an effort to investigate whether member distance from their primary care provider's (pcp) office was a factor in the count. Google Maps API was used to provide coordinates and distances were measured using Alteryx. This analysis was restricted to members living in the five boroughs of New York City and Long Island. Due to the nature of public transportation in the city, distances associated with public transit were measured as well. The conclusion was that although member to pcp distance was significant using both logistic regression and negative binomial general linear models, the effect size was negligibile and thus could not largely influence certain individuals that had multiple preventable admissions over the years. 


&nbsp;

### NYC Airbnb
#### April - May 2018

&nbsp;

New York City Airbnb listings were taken from Jeff Goldsmith's [Data Science I website](http://p8105.com/dataset_airbnb.html) and used to investigate what influences the price of a listing in addition to whether borough can be predicting using the available covariates. The full report containing the findings can be found [here](kaddabbo.github.io/airbnb_report.pdf)

&nbsp;

### US Twitter
#### November - December 2017

&nbsp;

An aggregate of tweets across a 48 hour period from Twitter users exclusively in the United States were obtained from [followthehashtag.com](http://www.followthehashtag.com/datasets/free-twitter-dataset-usa-200000-free-usa-tweets/). Sentiment analysis was completed and various visualizations were created and evaluated. The website hosting the results of the group's exploratory analysis can be found [here](https://k-maciejewski.github.io/p8105_final_website/index.html), in addition to the compiled report viewed [here](kaddabbo.github.io/twitter_report.html).